angular.module('commentMockModule', [])
  .constant('commentsMock', [
    [
      {
        'url': 'https://api.github.com/repos/Dica-Developer/gh-review/comments/8298345',
        'html_url': 'https://github.com/Dica-Developer/gh-review/commit/5a08fa2c4b12b49c02fca1f340412e68c8763770#commitcomment-8298345',
        'id': 8298345,
        'user': {
          'login': 'JayGray',
          'id': 675206,
          'avatar_url': 'https://avatars.githubusercontent.com/u/675206?v=3',
          'gravatar_id': '',
          'url': 'https://api.github.com/users/JayGray',
          'html_url': 'https://github.com/JayGray',
          'followers_url': 'https://api.github.com/users/JayGray/followers',
          'following_url': 'https://api.github.com/users/JayGray/following{/other_user}',
          'gists_url': 'https://api.github.com/users/JayGray/gists{/gist_id}',
          'starred_url': 'https://api.github.com/users/JayGray/starred{/owner}{/repo}',
          'subscriptions_url': 'https://api.github.com/users/JayGray/subscriptions',
          'organizations_url': 'https://api.github.com/users/JayGray/orgs',
          'repos_url': 'https://api.github.com/users/JayGray/repos',
          'events_url': 'https://api.github.com/users/JayGray/events{/privacy}',
          'received_events_url': 'https://api.github.com/users/JayGray/received_events',
          'type': 'User',
          'site_admin': false
        },
        'position': 9,
        'line': 2,
        'path': 'app/templates/file.html',
        'commit_id': '5a08fa2c4b12b49c02fca1f340412e68c8763770',
        'created_at': '2014-10-24T21:42:16Z',
        'updated_at': '2014-10-24T21:42:16Z',
        'body_html': '<p>I would like to see styling in less files only. <img class="emoji" title=":stuck_out_tongue:" alt=":stuck_out_tongue:" src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f61b.png" height="20" width="20" align="absmiddle"></p>',
        'body_text': 'I would like to see styling in less files only.',
        'body': 'I would like to see styling in less files only. :stuck_out_tongue:'
      },
      {
        'url': 'https://api.github.com/repos/Dica-Developer/gh-review/comments/8298346',
        'html_url': 'https://github.com/Dica-Developer/gh-review/commit/5a08fa2c4b12b49c02fca1f340412e68c8763770#commitcomment-8298346',
        'id': 8298346,
        'user': {
          'login': 'JayGray',
          'id': 675206,
          'avatar_url': 'https://avatars.githubusercontent.com/u/675206?v=3',
          'gravatar_id': '',
          'url': 'https://api.github.com/users/JayGray',
          'html_url': 'https://github.com/JayGray',
          'followers_url': 'https://api.github.com/users/JayGray/followers',
          'following_url': 'https://api.github.com/users/JayGray/following{/other_user}',
          'gists_url': 'https://api.github.com/users/JayGray/gists{/gist_id}',
          'starred_url': 'https://api.github.com/users/JayGray/starred{/owner}{/repo}',
          'subscriptions_url': 'https://api.github.com/users/JayGray/subscriptions',
          'organizations_url': 'https://api.github.com/users/JayGray/orgs',
          'repos_url': 'https://api.github.com/users/JayGray/repos',
          'events_url': 'https://api.github.com/users/JayGray/events{/privacy}',
          'received_events_url': 'https://api.github.com/users/JayGray/received_events',
          'type': 'User',
          'site_admin': false
        },
        'position': null,
        'line': null,
        'path': null,
        'commit_id': '5a08fa2c4b12b49c02fca1f340412e68c8763770',
        'created_at': '2014-10-24T21:42:27Z',
        'updated_at': '2014-10-24T21:42:27Z',
        'body_html': '<div class="highlight highlight-json"><pre>{\n  <span class="pl-s1"><span class="pl-pds">"</span>version<span class="pl-pds">"</span></span>: <span class="pl-s1"><span class="pl-pds">"</span>0.6.2<span class="pl-pds">"</span></span>,\n  <span class="pl-s1"><span class="pl-pds">"</span>approved<span class="pl-pds">"</span></span>: <span class="pl-c1">true</span>,\n  <span class="pl-s1"><span class="pl-pds">"</span>approver<span class="pl-pds">"</span></span>: <span class="pl-s1"><span class="pl-pds">"</span>JayGray<span class="pl-pds">"</span></span>,\n  <span class="pl-s1"><span class="pl-pds">"</span>approvalDate<span class="pl-pds">"</span></span>: <span class="pl-c1">1414186947435</span>\n}</pre></div>\n\n<p>approved with <a href="http://gh-review.herokuapp.com/">gh-review</a></p>',
        'body_text': '{\n  "version": "0.6.2",\n  "approved": true,\n  "approver": "JayGray",\n  "approvalDate": 1414186947435\n}\n\napproved with gh-review',
        'body': '```json\n{\n  "version": "0.6.2",\n  "approved": true,\n  "approver": "JayGray",\n  "approvalDate": 1414186947435\n}\n```\napproved with [gh-review](http://gh-review.herokuapp.com/)'
      },
      {
        'url': 'https://api.github.com/repos/Dica-Developer/gh-review/comments/8300960',
        'html_url': 'https://github.com/Dica-Developer/gh-review/commit/5a08fa2c4b12b49c02fca1f340412e68c8763770#commitcomment-8300960',
        'id': 8300960,
        'user': {
          'login': 'mschaaf',
          'id': 703355,
          'avatar_url': 'https://avatars.githubusercontent.com/u/703355?v=3',
          'gravatar_id': '',
          'url': 'https://api.github.com/users/mschaaf',
          'html_url': 'https://github.com/mschaaf',
          'followers_url': 'https://api.github.com/users/mschaaf/followers',
          'following_url': 'https://api.github.com/users/mschaaf/following{/other_user}',
          'gists_url': 'https://api.github.com/users/mschaaf/gists{/gist_id}',
          'starred_url': 'https://api.github.com/users/mschaaf/starred{/owner}{/repo}',
          'subscriptions_url': 'https://api.github.com/users/mschaaf/subscriptions',
          'organizations_url': 'https://api.github.com/users/mschaaf/orgs',
          'repos_url': 'https://api.github.com/users/mschaaf/repos',
          'events_url': 'https://api.github.com/users/mschaaf/events{/privacy}',
          'received_events_url': 'https://api.github.com/users/mschaaf/received_events',
          'type': 'User',
          'site_admin': false
        },
        'position': 9,
        'line': 2,
        'path': 'app/templates/file.html',
        'commit_id': '5a08fa2c4b12b49c02fca1f340412e68c8763770',
        'created_at': '2014-10-25T06:16:49Z',
        'updated_at': '2014-10-25T06:16:49Z',
        'body_html': '<p>Yes I am too but I sleep better with late night success. ;-)</p>',
        'body_text': 'Yes I am too but I sleep better with late night success. ;-)',
        'body': 'Yes I am too but I sleep better with late night success. ;-)'
      }
    ]
  ]);
